CREATE TABLE temp_Users (id varchar UNIQUE, user_name varchar, user_hash bit NOT NULL DEFAULT (0), system_generated_password bit NOT NULL DEFAULT (0), pwd_last_changed datetimeoffset, authenticate_id varchar, sugar_login bit NOT NULL DEFAULT (0), picture varchar, first_name varchar, last_name varchar, full_name varchar, name varchar, is_admin bit NOT NULL DEFAULT (0), external_auth_only bit NOT NULL DEFAULT (0), receive_notifications bit NOT NULL DEFAULT (0), description text, date_entered datetimeoffset, date_modified datetimeoffset, last_login datetimeoffset, modified_user_id varchar, modified_by_name varchar, created_by varchar, created_by_name varchar, created_by_link varchar, title varchar, department varchar, phone_home varchar, phone_mobile varchar, phone_work varchar, phone_other varchar, phone_fax varchar, status varchar, address_street text, address_city varchar, address_state varchar, address_country varchar, address_postalcode varchar, UserType varchar, default_team varchar, team_id varchar, team_set_id varchar, team_count varchar, team_name varchar, team_link varchar, default_primary_team varchar, team_count_link varchar, teams varchar, team_memberships varchar, team_sets varchar, users_signatures varchar, deleted bit NOT NULL DEFAULT (0), portal_only bit NOT NULL DEFAULT (0), show_on_employees bit NOT NULL DEFAULT (0), employee_status varchar, messenger_id varchar, messenger_type varchar, calls varchar, kbusefulness varchar, meetings varchar, contacts_sync varchar, reports_to_id varchar, reports_to_name varchar, reports_to_link varchar, reportees varchar, email1 varchar, email varchar, email_addresses varchar, email_addresses_primary varchar, email_link_type varchar, aclroles varchar, is_group bit NOT NULL DEFAULT (0), c_accept_status_fields varchar, m_accept_status_fields varchar, accept_status_id varchar, accept_status_name varchar, accept_status_calls varchar, accept_status_meetings varchar, prospect_lists varchar, emails_users varchar, holidays varchar, eapm varchar, oauth_tokens varchar, project_resource varchar, quotas varchar, forecasts varchar, preferred_language varchar, activities varchar, acl_role_set_id varchar, acl_role_sets varchar)
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('7356c075-64ba-3360-cc69-5638a0aff5e9','jduggan',0,0,'2017-02-28T17:16:00-05:00','  ',0,'  ','John','Duggan','John Duggan','John Duggan',0,0,0,'  ','2015-11-03T06:53:10-05:00','2017-02-28T18:00:45-05:00','2017-02-28T17:13:00-05:00','7356c075-64ba-3360-cc69-5638a0aff5e9','  ','de7abf3e-aba1-6426-84bc-56324780597c','Linda White','null','Vice President Australia / New Zealand','  ','  ','+61 438 386 190 ','+61 438 386 190','  ','  ','Active','  ','  ','  ','  ','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','  ','  ','null','undefined','null','undefined','3f4094c0-2a05-7271-0de6-5543b483ff45','Clive Bourke','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('13083c65-6ac6-b042-5b7b-56df14fd79e0','nhallas',0,0,'2017-02-13T07:37:48-05:00','  ',0,'  ','Nick','Hallas','Nick Hallas','Nick Hallas',0,0,0,'  ','2016-03-08T13:06:10-05:00','2017-02-13T07:37:48-05:00','2017-02-14T11:28:03-05:00','13083c65-6ac6-b042-5b7b-56df14fd79e0','  ','1','Mike Groat','null','Director of Sales, East Coast','Americas Sales','  ','  ','  ','  ','  ','Active','  ','  ','  ','  ','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','  ','  ','null','undefined','null','undefined','9c0a781b-786c-70e9-d452-5550c0d1b548','Bob Long','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('de7abf3e-aba1-6426-84bc-56324780597c','LWhite',0,0,'2017-02-08T05:12:52-05:00','  ',0,'  ','Linda','White','Linda White','Linda White',0,0,0,'Skype','2015-10-29T12:20:42-04:00','2017-02-08T05:12:52-05:00','2017-02-09T09:40:21-05:00','de7abf3e-aba1-6426-84bc-56324780597c','  ','3f4094c0-2a05-7271-0de6-5543b483ff45','Clive Bourke','null','  ','  ','  ','+353 87 2461730','+353 57 86 87622','+44 1273 254 001','  ','Active','  ','  ','  ','  ','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','lisa.clooney','  ','null','undefined','null','undefined','3f4094c0-2a05-7271-0de6-5543b483ff45','Clive Bourke','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('28df29ec-81c8-d80e-ef75-56374670cf4f','coneill',0,0,'2017-02-07T09:07:08-05:00','  ',0,'  ','Colin','O Neill','Colin O Neill','Colin O Neill',0,0,0,'  ','2015-11-02T06:17:09-05:00','2017-02-07T09:07:08-05:00','2017-02-08T09:01:55-05:00','de7abf3e-aba1-6426-84bc-56324780597c','  ','de7abf3e-aba1-6426-84bc-56324780597c','Linda White','null','EMEA Sales','  ','  ','+353 87 799 6624','+353 1 818 1652','  ','  ','Active','  ','  ','  ','  ','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','  ','  ','null','undefined','null','undefined','3f4094c0-2a05-7271-0de6-5543b483ff45','Clive Bourke','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('b798ebf2-0029-bd47-5d6d-5270104be5d3','cwhite',0,0,'2017-01-30T21:30:26-05:00','  ',0,'  ','Conor','White','Conor White','Conor White',0,0,0,'  ','2013-10-29T15:47:32-04:00','2017-01-30T21:30:26-05:00','2017-01-22T12:07:36-05:00','b798ebf2-0029-bd47-5d6d-5270104be5d3','  ','1','Mike Groat','null','  ','  ','  ','  ','  ','  ','  ','Active','  ','  ','  ','  ','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','  ','  ','null','undefined','null','undefined','  ','  ','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','en_us','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('9c0a781b-786c-70e9-d452-5550c0d1b548','blong',0,0,'2017-01-29T16:33:55-05:00','  ',0,'  ','Bob','Long','Bob Long','Bob Long',0,0,0,'  ','2015-05-11T10:45:03-04:00','2017-01-29T16:33:55-05:00','2017-02-20T18:41:33-05:00','9c0a781b-786c-70e9-d452-5550c0d1b548','  ','1','Mike Groat','null','VP Sales','  ','  ','720-545-6270','720-545-6270','303-658-0785','  ','Active','  ','  ','  ','  ','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','  ','  ','null','undefined','null','undefined','b798ebf2-0029-bd47-5d6d-5270104be5d3','Conor White','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('1','admin',0,0,'2017-01-23T11:55:02-05:00','  ',0,'70edc1d1-16b5-a7e1-87f4-5550c1f76578','Mike','Groat','Mike Groat','Mike Groat',0,0,0,'  ','2013-10-25T19:27:55-04:00','2017-01-23T11:55:02-05:00','2017-03-03T16:06:49-05:00','1','  ','  ','  ','null','Administrator','Sales','  ','703-628-5210','703-984-4036','  ','  ','Active','11911 Freedom Drive, Ste 900','Reston','VA','USA','20190','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','  ','  ','null','undefined','null','undefined','9c0a781b-786c-70e9-d452-5550c0d1b548','Bob Long','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','en_us','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('ea7c60c9-e79a-fd05-9838-578e5302fe50','rpsoden',0,0,'2017-01-19T19:17:24-05:00','  ',0,'  ','Robert','Soden','Robert Soden','Robert Soden',0,0,0,'  ','2016-07-19T12:22:04-04:00','2017-01-19T19:17:24-05:00','2017-01-19T19:16:52-05:00','ea7c60c9-e79a-fd05-9838-578e5302fe50','  ','de7abf3e-aba1-6426-84bc-56324780597c','Linda White','null','Sales Director, Asia Pacific','  ','  ','+852 9304 6699 ','+852 8226 5660 ','  ','  ','Active','  ','  ','  ','Hong Kong','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','robertsoden','  ','null','undefined','null','undefined','3f4094c0-2a05-7271-0de6-5543b483ff45','Clive Bourke','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('3f4094c0-2a05-7271-0de6-5543b483ff45','cbourke',0,0,'2017-01-18T10:45:30-05:00','  ',0,'  ','Clive','Bourke','Clive Bourke','Clive Bourke',0,0,0,'  ','2015-05-01T13:12:36-04:00','2017-01-18T10:45:30-05:00','2017-02-06T10:05:27-05:00','de7abf3e-aba1-6426-84bc-56324780597c','  ','1','Mike Groat','null','President','  ','  ','+353 (86) 835 2127','+353 018181661','  ','  ','Active','  ','  ','  ','  ','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','  ','  ','null','undefined','null','undefined','  ','  ','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('73743558-e8f5-78ef-cdc9-579721faea92','gventer',0,0,'2017-01-06T01:28:28-05:00','  ',0,'  ','Guy','Venter','Guy Venter','Guy Venter',0,0,0,'  ','2016-07-26T04:40:02-04:00','2017-01-06T01:28:28-05:00','2017-02-10T03:07:57-05:00','73743558-e8f5-78ef-cdc9-579721faea92','  ','de7abf3e-aba1-6426-84bc-56324780597c','Linda White','null','Regional Manager, South Africa','  ','+27 12 735 2357','+27 82 658 8446','+27826588446','  ','  ','Active','Dinokeng area','  ','Gauteng','South Africa','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','  ','  ','null','undefined','null','undefined','3f4094c0-2a05-7271-0de6-5543b483ff45','Clive Bourke','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('e2c35b0a-5fe4-25f4-be6b-5669ec3740ee','gchase',0,0,'2017-01-03T10:10:50-05:00','  ',0,'  ','Greg','Chase','Greg Chase','Greg Chase',0,0,0,'  ','2015-12-10T16:21:37-05:00','2017-01-03T10:10:50-05:00','2017-01-05T20:59:06-05:00','1','  ','1','Mike Groat','null','  ','  ','  ','  ','303-949-2319','  ','  ','Active','  ','  ','  ','  ','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','  ','  ','null','undefined','null','undefined','9c0a781b-786c-70e9-d452-5550c0d1b548','Bob Long','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('c79b078f-9b48-d91c-3563-54ad53f32577','lring',0,0,'2016-12-31T11:25:59-05:00','  ',0,'  ','Leo','Ring','Leo Ring','Leo Ring',0,0,0,'  ','2015-01-07T10:40:57-05:00','2016-12-31T11:25:59-05:00','2017-03-02T14:38:02-05:00','c79b078f-9b48-d91c-3563-54ad53f32577','  ','1','Mike Groat','null','VP Sales Americas','Sales','  ','  ','2024136287','  ','  ','Active','  ','  ','  ','  ','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','  ','  ','null','undefined','null','undefined','9c0a781b-786c-70e9-d452-5550c0d1b548','Bob Long','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('8737c847-86cf-8446-33dd-52792f838376','twachter',0,0,'2016-12-12T11:23:42-05:00','  ',0,'  ','Travis','Wachter','Travis Wachter','Travis Wachter',0,0,0,'  ','2013-11-05T12:50:35-05:00','2016-12-12T11:23:42-05:00','2017-01-11T16:01:42-05:00','8737c847-86cf-8446-33dd-52792f838376','  ','1','Mike Groat','null','  ','  ','  ','  ','  ','  ','  ','Active','  ','  ','  ','  ','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','  ','  ','null','undefined','null','undefined','  ','  ','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','en_us','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('11792012-f6d3-a9b2-9b32-56df15142f6d','bshomaker',0,0,'2016-12-08T13:57:45-05:00','  ',0,'  ','Brett','Schomaker','Brett Schomaker','Brett Schomaker',0,0,0,'  ','2016-03-08T13:08:28-05:00','2016-12-08T13:57:45-05:00','2016-12-08T14:58:08-05:00','1','  ','1','Mike Groat','null','Director of Sales, West Coast','Americas Sales','  ','  ','623-670-4319','  ','  ','Active','  ','  ','  ','  ','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','  ','  ','null','undefined','null','undefined','9c0a781b-786c-70e9-d452-5550c0d1b548','Bob Long','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('e68bc779-81cf-3454-61a1-56389c0df994','mwatson',0,0,'2016-12-04T20:55:25-05:00','  ',0,'  ','Michael','Watson','Michael Watson','Michael Watson',0,0,0,'  ','2015-11-03T06:38:41-05:00','2016-12-04T20:55:25-05:00','2016-12-04T20:54:51-05:00','e68bc779-81cf-3454-61a1-56389c0df994','  ','de7abf3e-aba1-6426-84bc-56324780597c','Linda White','null','Pre-Sales Solution Architect','  ','  ','+61 409 730 941','+61 26230 0950','  ','  ','Active','  ','  ','  ','  ','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','  ','  ','null','undefined','null','undefined','  ','  ','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('c3c0746d-987c-7e8b-1d37-563729a36cb9','EGilmore',0,0,'2016-11-14T05:58:42-05:00','  ',0,'  ','Eric','Gilmore','Eric Gilmore','Eric Gilmore',0,0,0,'  ','2015-11-02T04:13:14-05:00','2016-11-14T05:58:42-05:00','2016-11-14T05:55:21-05:00','de7abf3e-aba1-6426-84bc-56324780597c','  ','de7abf3e-aba1-6426-84bc-56324780597c','Linda White','null','Head of Pre-Sales Consulting, EMEA','  ','  ','+353 86 826 0582','+353 1 818 1618','  ','  ','Active','  ','  ','  ','  ','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','  ','  ','null','undefined','null','undefined','3f4094c0-2a05-7271-0de6-5543b483ff45','Clive Bourke','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('61790359-1ece-2bb2-3faf-5500a10412a7','reports',0,0,'2016-07-29T11:27:00-04:00','  ',0,'  ','Terrassa','Asare','Terrassa Asare','Terrassa Asare',0,0,0,'  ','2015-03-11T16:11:17-04:00','2016-10-24T13:36:22-04:00','2017-03-07T09:05:47-05:00','1','  ','1','Mike Groat','null','  ','  ','  ','  ','1-703-984-4007','  ','  ','Active','  ','  ','  ','  ','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','  ','  ','null','undefined','null','undefined','  ','  ','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('d00c3d24-5ce0-8fe5-eb0d-575823f66d96','lbalogun',0,0,'2016-08-15T11:14:00-04:00','  ',0,'  ','Luqman','Balogun','Luqman Balogun','Luqman Balogun',0,0,0,'  ','2016-06-08T09:52:56-04:00','2016-09-07T08:53:38-04:00','2016-08-16T06:53:00-04:00','d00c3d24-5ce0-8fe5-eb0d-575823f66d96','  ','de7abf3e-aba1-6426-84bc-56324780597c','Linda White','null','Divisional Director, Africa','  ','  ','+234 703 411 0627','+23412719113*424','  ','  ','Active','  ','  ','  ','Nigeria','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','luq.bal','  ','null','undefined','null','undefined','3f4094c0-2a05-7271-0de6-5543b483ff45','Clive Bourke','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('8e0bca86-7258-4c03-f3b0-568a454483ed','scook',0,0,'2016-01-04T05:13:00-05:00','  ',0,'  ','Steve','Cook','Steve Cook','Steve Cook',0,0,0,'  ','2016-01-04T05:13:09-05:00','2016-01-04T05:14:57-05:00','2016-01-10T04:44:04-05:00','8e0bca86-7258-4c03-f3b0-568a454483ed','  ','de7abf3e-aba1-6426-84bc-56324780597c','Linda White','null','Consultant','  ','  ','0044 7768 152 422','  ','  ','  ','Active','  ','  ','  ','  ','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','steve.cooook','  ','null','undefined','null','undefined','3f4094c0-2a05-7271-0de6-5543b483ff45','Clive Bourke','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
INSERT INTO temp_Users (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets) VALUES ('b8ea0dc1-9379-d383-de5e-550c52b11d8b','ddonohue',0,0,'2015-05-04T09:35:05-04:00','  ',0,'  ','Diana','Donohue','Diana Donohue','Diana Donohue',0,0,0,'  ','2015-03-20T13:01:45-04:00','2015-05-04T09:35:05-04:00','2016-04-19T16:24:17-04:00','1','  ','1','Mike Groat','null','  ','  ','  ','  ','7039844015','  ','  ','Active','  ','  ','  ','  ','  ','  ','1','undefined','undefined','  ','team name','undefined','undefined','null','undefined','undefined','undefined','undefined',0,0,0,'Active','  ','  ','null','undefined','null','undefined','  ','  ','null','undefined','  ','[object Object]','undefined','undefined','  ','undefined',0,'  ','  ','  ','  ','  ','  ','undefined','undefined','undefined','undefined','undefined','undefined','undefined','undefined','  ','undefined','  ','undefined','undefined');
MERGE Users AS T
        USING temp_Users AS M
        ON T.id = M.id
WHEN MATCHED
THEN
        UPDATE SET T.id = M.id,
        T.user_name = M.user_name,
        T.user_hash = M.user_hash,
        T.system_generated_password = M.system_generated_password,
        T.pwd_last_changed = M.pwd_last_changed,
        T.authenticate_id = M.authenticate_id,
        T.sugar_login = M.sugar_login,
        T.picture = M.picture,
        T.first_name = M.first_name,
        T.last_name = M.last_name,
        T.full_name = M.full_name,
        T.name = M.name,
        T.is_admin = M.is_admin,
        T.external_auth_only = M.external_auth_only,
        T.receive_notifications = M.receive_notifications,
        T.description = M.description,
        T.date_entered = M.date_entered,
        T.date_modified = M.date_modified,
        T.last_login = M.last_login,
        T.modified_user_id = M.modified_user_id,
        T.modified_by_name = M.modified_by_name,
        T.created_by = M.created_by,
        T.created_by_name = M.created_by_name,
        T.created_by_link = M.created_by_link,
        T.title = M.title,
        T.department = M.department,
        T.phone_home = M.phone_home,
        T.phone_mobile = M.phone_mobile,
        T.phone_work = M.phone_work,
        T.phone_other = M.phone_other,
        T.phone_fax = M.phone_fax,
        T.status = M.status,
        T.address_street = M.address_street,
        T.address_city = M.address_city,
        T.address_state = M.address_state,
        T.address_country = M.address_country,
        T.address_postalcode = M.address_postalcode,
        T.UserType = M.UserType,
        T.default_team = M.default_team,
        T.team_id = M.team_id,
        T.team_set_id = M.team_set_id,
        T.team_count = M.team_count,
        T.team_name = M.team_name,
        T.team_link = M.team_link,
        T.default_primary_team = M.default_primary_team,
        T.team_count_link = M.team_count_link,
        T.teams = M.teams,
        T.team_memberships = M.team_memberships,
        T.team_sets = M.team_sets,
        T.users_signatures = M.users_signatures,
        T.deleted = M.deleted,
        T.portal_only = M.portal_only,
        T.show_on_employees = M.show_on_employees,
        T.employee_status = M.employee_status,
        T.messenger_id = M.messenger_id,
        T.messenger_type = M.messenger_type,
        T.calls = M.calls,
        T.kbusefulness = M.kbusefulness,
        T.meetings = M.meetings,
        T.contacts_sync = M.contacts_sync,
        T.reports_to_id = M.reports_to_id,
        T.reports_to_name = M.reports_to_name,
        T.reports_to_link = M.reports_to_link,
        T.reportees = M.reportees,
        T.email1 = M.email1,
        T.email = M.email,
        T.email_addresses = M.email_addresses,
        T.email_addresses_primary = M.email_addresses_primary,
        T.email_link_type = M.email_link_type,
        T.aclroles = M.aclroles,
        T.is_group = M.is_group,
        T.c_accept_status_fields = M.c_accept_status_fields,
        T.m_accept_status_fields = M.m_accept_status_fields,
        T.accept_status_id = M.accept_status_id,
        T.accept_status_name = M.accept_status_name,
        T.accept_status_calls = M.accept_status_calls,
        T.accept_status_meetings = M.accept_status_meetings,
        T.prospect_lists = M.prospect_lists,
        T.emails_users = M.emails_users,
        T.holidays = M.holidays,
        T.eapm = M.eapm,
        T.oauth_tokens = M.oauth_tokens,
        T.project_resource = M.project_resource,
        T.quotas = M.quotas,
        T.forecasts = M.forecasts,
        T.preferred_language = M.preferred_language,
        T.activities = M.activities,
        T.acl_role_set_id = M.acl_role_set_id,
        T.acl_role_sets = M.acl_role_sets
WHEN NOT MATCHED
THEN
        INSERT (id, user_name, user_hash, system_generated_password, pwd_last_changed, authenticate_id, sugar_login, picture, first_name, last_name, full_name, name, is_admin, external_auth_only, receive_notifications, description, date_entered, date_modified, last_login, modified_user_id, modified_by_name, created_by, created_by_name, created_by_link, title, department, phone_home, phone_mobile, phone_work, phone_other, phone_fax, status, address_street, address_city, address_state, address_country, address_postalcode, UserType, default_team, team_id, team_set_id, team_count, team_name, team_link, default_primary_team, team_count_link, teams, team_memberships, team_sets, users_signatures, deleted, portal_only, show_on_employees, employee_status, messenger_id, messenger_type, calls, kbusefulness, meetings, contacts_sync, reports_to_id, reports_to_name, reports_to_link, reportees, email1, email, email_addresses, email_addresses_primary, email_link_type, aclroles, is_group, c_accept_status_fields, m_accept_status_fields, accept_status_id, accept_status_name, accept_status_calls, accept_status_meetings, prospect_lists, emails_users, holidays, eapm, oauth_tokens, project_resource, quotas, forecasts, preferred_language, activities, acl_role_set_id, acl_role_sets)
        VALUES ( M.id, M.user_name, M.user_hash, M.system_generated_password, M.pwd_last_changed, M.authenticate_id, M.sugar_login, M.picture, M.first_name, M.last_name, M.full_name, M.name, M.is_admin, M.external_auth_only, M.receive_notifications, M.description, M.date_entered, M.date_modified, M.last_login, M.modified_user_id, M.modified_by_name, M.created_by, M.created_by_name, M.created_by_link, M.title, M.department, M.phone_home, M.phone_mobile, M.phone_work, M.phone_other, M.phone_fax, M.status, M.address_street, M.address_city, M.address_state, M.address_country, M.address_postalcode, M.UserType, M.default_team, M.team_id, M.team_set_id, M.team_count, M.team_name, M.team_link, M.default_primary_team, M.team_count_link, M.teams, M.team_memberships, M.team_sets, M.users_signatures, M.deleted, M.portal_only, M.show_on_employees, M.employee_status, M.messenger_id, M.messenger_type, M.calls, M.kbusefulness, M.meetings, M.contacts_sync, M.reports_to_id, M.reports_to_name, M.reports_to_link, M.reportees, M.email1, M.email, M.email_addresses, M.email_addresses_primary, M.email_link_type, M.aclroles, M.is_group, M.c_accept_status_fields, M.m_accept_status_fields, M.accept_status_id, M.accept_status_name, M.accept_status_calls, M.accept_status_meetings, M.prospect_lists, M.emails_users, M.holidays, M.eapm, M.oauth_tokens, M.project_resource, M.quotas, M.forecasts, M.preferred_language, M.activities, M.acl_role_set_id, M.acl_role_sets);
